[package]
name = "lorem-ipsum"
version = "0.1.0"
edition = "2021"
publish = true

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
rand = { version = "0.8.5", features = [ "alloc" ] }
regex = "1.10.3"
